#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, in1,    pot_left,       sensorPotentiometer)
#pragma config(Sensor, in2,    pot_right,      sensorPotentiometer)
#pragma config(Motor,  port1,           RightLift1,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           LeftLift1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           Intake,        tmotorVex393, openLoop)
#pragma config(Motor,  port4,           FrontRight,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           LeftLift2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           RightLift2,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           Strafe,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           BackLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          BackRight,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////
//
//	FILE: large_robot.c
//	ORIGINAL AUTHOR: MH1613
//	DESCRIPTION: This file is a ROBOTC file, based on the competition control template
// 	from Vex Robotics. It defines how the robot should behave in autonomous mode without
//  user input, and how controls sent remotely should be interpreted.
//
//    MOTOR CONFIGURATION <NEW>
//			1. Right Lift 1								6. Left Lift 2
//			2. Left Lift 1								7. Right Lift 2
//			3. Intake (Y Cable)						8. Strafe (Y Cable)
//			4. Right Front Drive					9. Left Rear Drive
//			5. Left Front Drive						10. Right Rear Drive
//
//		COMMS CONFIGURATION
//
//			UART1. BeagleBone Link
//			UART2. LCD Screen
//			I2C.   Backup BeagleBone Link
//
//		SENSOR CONFIGURATION
//
//			1. (Analog) Left Lift Potentiometer
//			2. (Analog) Right Lift Potentiometer
//		TODO Rotary Encoders.
//
//
/////////////////////////////////////////////////////////////////////////////////////////

// Competition includes and defines
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"

// Public function definitions

void setup_lcd() {
	lcd_setup();
	// TODO: Add autonomous programs here
}

// pre_auton: Used to set up the robots with initial servo positions etc. before the
// start of the competition.
void pre_auton()
{
  bStopTasksBetweenModes = true;
}

// autonomous: defines how the robot behaves in autonomous mode.
task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

// usercontrol: Defines how the robot reacts to user input sent from a remote control
task usercontrol()
{


	while (true)
	{

		int left_lift_rate, right_lift_rate;
		left_lift_rate = vexRT[Ch3];
		right_lift_rate = vexRT[Ch4];

		motor[LeftLift1] = left_lift_rate;
		motor[RightLift1] = right_lift_rate;
		motor[LeftLift2] = left_lift_rate;
		motor[RightLift2] = right_lift_rate;

		update_direction(state_direction, direction);

		wait1Msec(50);
	}
}
